apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: polfor/guu_band
    newName: polfor/guu_band_dev
    newTag: 59dc5c0

namespace: dev

patchesStrategicMerge:
  - hpa.yml
