apiVersion: apps/v1
kind: Deployment
metadata:
  name: guu-band
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: guu-band
          image: polfor/guu_band_dev
          newTag: f7e6721
