apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: polfor/guu_band
    newTag: d8bd77d

replicas:
  - name: guu-band
    count: 3

namespace: prod
