apiVersion: apps/v1
kind: Deployment
metadata:
  name: guu-band
  namespace: prod
spec:
  template:
    spec:
      containers:
        - name: guu-band
          image: polfor/guu_band
          newTag: adc6e04
