apiVersion: autoscaling/vl
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-guu-band
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guu-band
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
